name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Run container in detached mode
      run: docker run -d --name my-running-app my-image-name:$(date +%s)

    - name: Display running containers
      run: docker ps

    - name: Run bundle install inside container
      run: docker exec my-running-app bundle install

    - name: Check logs of the running container
      run: docker logs my-running-app

    - name: Stop and remove container
      run: |
        docker stop my-running-app
        docker rm my-running-app
